In [ ]:
#importing numpy and pandas
import numpy as np
import pandas as pd

#importing for visualization
import matplotlib.pyplot as plt

%matplotlib inline

r_s=123456

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Epileptic Seizure Recognition.csv")
df

Unnamed   X1   X2   X3   X4   X5   X6   X7   X8   X9  ...  X170  \
0      X21.V1.791  135  190  229  223  192  125   55   -9  -33  ...   -17   
1      X15.V1.924  386  382  356  331  320  315  307  272  244  ...   164   
2         X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85  ...    57   
3       X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87  ...   -82   
4       X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21  ...     4   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
11495  X22.V1.114  -22  -22  -23  -26  -36  -42  -45  -42  -45  ...    15   
11496  X19.V1.354  -47  -11   28   77  141  211  246  240  193  ...   -65   
11497    X8.V1.28   14    6  -13  -16   10   26   27   -9    4  ...   -65   
11498  X10.V1.932  -40  -25   -9  -12   -2   12    7   19   22  ...   121   
11499  X16.V1.210   29   41   57   72   74   62   54   43   31  ...   -59   

       X171  X172  X173  X174  X175  X176  X177  X178  y  
0       -15   -31   -77  -103  -127  -116   -83   -51  4  
1       150   146   152   157   156   154   143   129  1  
2        64    48    19   -12   -30   -35   -35   -36  5  
3       -81   -80   -77   -85   -77   -72   -69   -65  5  
4         2   -12   -32   -41   -65   -83   -89   -73  5  
...     ...   ...   ...   ...   ...   ...   ...   ... ..  
11495    16    12     5    -1   -18   -37   -47   -48  2  
11496   -33    -7    14    27    48    77   117   170  1  
11497   -48   -61   -62   -67   -30    -2    -1    -8  5  
11498   135   148   143   116    86    68    59    55  3  
11499   -25    -4     2     5     4    -2     2    20  4  

[11500 rows x 180 columns]

In [ ]:
df.isnull().values.any()

False

In [ ]:
#Dropping the 'Unnamed: 0' column
# df.drop('Unnamed: 0',inplace=True,axis=1)

KeyError: ignored

In [ ]:
#target variable
y=df['y']

In [ ]:
y=df['y']
y = y.apply(lambda x: 1 if x == 1 else 0)
y.unique()

array([0, 1])

In [ ]:
X=df.drop('y',axis=1)
X.head()

Unnamed   X1   X2   X3   X4   X5   X6   X7   X8   X9  ...  X169  X170  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33  ...     8   -17   
1  X15.V1.924  386  382  356  331  320  315  307  272  244  ...   168   164   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85  ...    29    57   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87  ...   -80   -82   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21  ...    10     4   

   X171  X172  X173  X174  X175  X176  X177  X178  
0   -15   -31   -77  -103  -127  -116   -83   -51  
1   150   146   152   157   156   154   143   129  
2    64    48    19   -12   -30   -35   -35   -36  
3   -81   -80   -77   -85   -77   -72   -69   -65  
4     2   -12   -32   -41   -65   -83   -89   -73  

[5 rows x 179 columns]

In [ ]:
import pandas as pd

# Assuming you have a DataFrame X, you can drop non-numeric columns like this:
numeric_columns = X.select_dtypes(include=['number'])  # Select numeric columns
X_numeric = X[numeric_columns.columns]  # Create a DataFrame with only numeric columns
from sklearn.preprocessing import StandardScaler

# Scale the numeric data
scale = StandardScaler().fit(X_numeric)
x_scaled = scale.transform(X_numeric)
x_scaled

array([[ 0.88505134,  1.20992878,  1.46276429, ..., -0.63414367,
        -0.43329036, -0.23539922],
       [ 2.40057718,  2.36619038,  2.23944096, ...,  1.02342937,
         0.95424076,  0.85653664],
       [-0.12328657, -0.16915405, -0.22513147, ..., -0.13687176,
        -0.13859348, -0.14440456],
       ...,
       [ 0.1544592 ,  0.10184476, -0.01720228, ...,  0.0657205 ,
         0.07015014,  0.02545213],
       [-0.17159018, -0.08484331,  0.00725997, ...,  0.49546166,
         0.43852123,  0.40762968],
       [ 0.24502848,  0.31262161,  0.41088722, ...,  0.0657205 ,
         0.08856869,  0.19530882]])

In [ ]:

from sklearn.decomposition import PCA
pca = PCA(n_components=2)  #two component
principalComponents = pca.fit_transform(x_scaled)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])
principalDf.head()

principal component 1  principal component 2
0              -0.134559              -1.172633
1              -1.504327              -3.328479
2               0.498853              -0.258003
3              -0.170016               0.252333
4              -0.250022               0.109084

In [ ]:
#Concating Principal components and y varaible
PCAdf= pd.concat([principalDf, y], axis = 1)
PCAdf.head()

principal component 1  principal component 2  y
0              -0.134559              -1.172633  0
1              -1.504327              -3.328479  1
2               0.498853              -0.258003  0
3              -0.170016               0.252333  0
4              -0.250022               0.109084  0

T-sne is an another dimensionality reduction techinique

In [ ]:
from sklearn.manifold import TSNE

TNSEdf = TSNE(random_state=r_s).fit_transform(x_scaled)
TNSEdf.shape
tnsedf = pd.DataFrame(TNSEdf)
tnsedf['y']=y
tnsedf.head()

0          1  y
0 -10.342006  -4.442934  0
1 -47.152122  -2.611702  1
2 -24.815304  28.900930  0
3 -33.425632  50.714619  0
4  32.643612  11.726575  0

K-means

In [ ]:
#K-Means
from sklearn.cluster import KMeans

# Number of clusters
kmeans = KMeans(n_clusters=5)

Implementing kmeans in pca

In [ ]:
#implementing kmeans in pcadf
kmeansPCA = kmeans.fit(principalDf)
#Getting the cluster labels
labels = kmeans.predict(principalDf)
PK_df= PCAdf
PK_df['kclust']=labels
PK_df['kclust'].unique()

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([4, 3, 1, 2, 0], dtype=int32)

Implementing kmeans in T-SNE

In [ ]:
#K-Means
from sklearn.cluster import KMeans
# Number of clusters
kmeans = KMeans(n_clusters=5)
#implementing kmeans in tnsedf
kmeanstnse = kmeans.fit(TNSEdf)
#Getting the cluster labels
k_labels = kmeans.predict(TNSEdf)


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
TK_df = tnsedf
TK_df['cluster']=k_labels
TK_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   0        11500 non-null  float32
 1   1        11500 non-null  float32
 2   y        11500 non-null  int64  
 3   cluster  11500 non-null  int32  
dtypes: float32(2), int32(1), int64(1)
memory usage: 224.7 KB


In [ ]:
TK_df['cluster'].unique()

array([3, 0, 1, 4, 2], dtype=int32)

Splitting the data into train and test

In [ ]:
#splitting into x and y varialbles

pk_x=PK_df.loc[:,['principal component 1','principal component 2','kclust']]
pk_y=PK_df['y']

tk_x=TK_df.loc[:,[0,1,'cluster']]
tk_y=TK_df['y']

In [ ]:
from sklearn.model_selection import train_test_split

#PCA +k-means
pkx_train, pkx_test, pky_train, pky_test = train_test_split(pk_x,pk_y,
test_size = 0.2,random_state = 101)

#T-SNE + k-means
tkx_train, tkx_test, tky_train, tky_test = train_test_split(tk_x,tk_y,
test_size = 0.2, random_state = 101)

metrix of classfication

In [ ]:
#Confusion matrix and accuraccy score
from sklearn.metrics import confusion_matrix, accuracy_score
#Cross validation
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

Logistic regression

In [ ]:
# Convert feature names to strings
tkx_train.columns = tkx_train.columns.astype(str)
tkx_test.columns = tkx_test.columns.astype(str)

# Now you can fit your logistic regression model
logmodel.fit(tkx_train, tky_train)
tklogpred = logmodel.predict(tkx_test)


In [ ]:
print(confusion_matrix(pky_test, pklogpred))
print(round(accuracy_score(pky_test, pklogpred),2)*100)

[[1866    0]
 [ 241  193]]
90.0


In [ ]:
print(confusion_matrix(tky_test, tklogpred))
print(round(accuracy_score(tky_test, tklogpred),2)*100)

[[1759  107]
 [ 288  146]]
83.0




```
# This is formatted as code
```

log(PCA + K-Means) gives the higher accuracy of 90.0

In [ ]:
#cross validation
LOGCV = (cross_val_score(logmodel, tkx_train, tky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

SVM

In [ ]:
from sklearn.svm import SVC
svc= SVC(kernel = 'sigmoid')
#There are various kernels linear,rbf
svc.fit(pkx_train, pky_train)
pspred = svc.predict(pkx_test)

svc.fit(tkx_train, tky_train)
tspred = svc.predict(tkx_test)

In [ ]:
print(confusion_matrix(pky_test, pspred))
print(round(accuracy_score(pky_test, pspred),2)*100)

print(confusion_matrix(tky_test, tspred))
print(round(accuracy_score(tky_test, tspred),2)*100)

[[1524  342]
 [ 345   89]]
70.0
[[1443  423]
 [ 362   72]]
66.0


SVM(PCA + k-means) gives the accuracy of 70.0

In [ ]:
SVCCV = (cross_val_score(svc, pkx_train, pky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 200)#criterion = entopy,gini

rfc.fit(pkx_train, pky_train)
prpred = rfc.predict(pkx_test)

rfc.fit(tkx_train, tky_train)
trpred = rfc.predict(tkx_test)

In [ ]:
print(confusion_matrix(tky_test, trpred))
print(round(accuracy_score(pky_test, prpred),2)*100)

print(confusion_matrix(tky_test, trpred))
print(round(accuracy_score(tky_test, trpred),2)*100)

[[1844   22]
 [  84  350]]
94.0
[[1844   22]
 [  84  350]]
95.0


RF(T-sne + k-Means) gives the higher accuracy of 95.0

In [ ]:
#Cross validation
RFCCV = (cross_val_score(rfc, tkx_train, tky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

In [ ]:
#NB
from sklearn.naive_bayes import GaussianNB
gaussiannb= GaussianNB()

gaussiannb.fit(pkx_train, pky_train)
pgpred = gaussiannb.predict(pkx_test)

gaussiannb.fit(tkx_train, tky_train)
tgpred = gaussiannb.predict(tkx_test)

In [ ]:
print(confusion_matrix(pky_test, pgpred))
print(round(accuracy_score(pky_test, pgpred),2)*100)

print(confusion_matrix(tky_test, tgpred))
print(round(accuracy_score(tky_test, tgpred),2)*100)

[[1847   19]
 [ 134  300]]
93.0
[[1779   87]
 [ 361   73]]
81.0


NB(PCA + k-means) gives as higher accuracy of 93.0

In [ ]:
NBCV = (cross_val_score(gaussiannb, pkx_train, pky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

In [ ]:
models = pd.DataFrame({
                'Models': ['Random Forest Classifier', 'Support Vector Machine','Logistic Model', 'Gausian NB',],
                'Score':  [RFCCV, SVCCV,LOGCV, NBCV]})

models.sort_values(by='Score', ascending=False)

Models     Score
0  Random Forest Classifier  0.949130
3                Gausian NB  0.932065
2            Logistic Model  0.824674
1    Support Vector Machine  0.677935